name: tubes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  intl_phone_number_input: ^0.7.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  permission_handler: ^11.3.1
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/reksadana.png
    - assets/images/sbnretail.png
    - assets/images/obligasifr.png
    - assets/images/saham.png
    - assets/icon/
    - assets/icon/admin.png
