// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWew575j52yEdKGdZvF5M8KEm2g2IoOmg',
    appId: '1:777451080167:android:4a9b8ab656390684641542',
    messagingSenderId: '777451080167',
    projectId: 'fir-aut-21102152',
    storageBucket: 'fir-aut-21102152.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7EJ7y7woEbAKIdjjcK5TS22ZsK8CT2Ng',
    appId: '1:777451080167:web:fa4861729c4a7cb3641542',
    messagingSenderId: '777451080167',
    projectId: 'fir-aut-21102152',
    authDomain: 'fir-aut-21102152.firebaseapp.com',
    storageBucket: 'fir-aut-21102152.appspot.com',
    measurementId: 'G-MBQ67NN13N',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbrmrtu1dsDKcERgeI8CAHgdivABTTgdw',
    appId: '1:777451080167:ios:ee8438fb94f2e424641542',
    messagingSenderId: '777451080167',
    projectId: 'fir-aut-21102152',
    storageBucket: 'fir-aut-21102152.appspot.com',
    iosBundleId: 'com.example.praktikum09FirebaseAuth',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbrmrtu1dsDKcERgeI8CAHgdivABTTgdw',
    appId: '1:777451080167:ios:ee8438fb94f2e424641542',
    messagingSenderId: '777451080167',
    projectId: 'fir-aut-21102152',
    storageBucket: 'fir-aut-21102152.appspot.com',
    iosBundleId: 'com.example.praktikum09FirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7EJ7y7woEbAKIdjjcK5TS22ZsK8CT2Ng',
    appId: '1:777451080167:web:5ba782d34108f84a641542',
    messagingSenderId: '777451080167',
    projectId: 'fir-aut-21102152',
    authDomain: 'fir-aut-21102152.firebaseapp.com',
    storageBucket: 'fir-aut-21102152.appspot.com',
    measurementId: 'G-7NQ0XDB14G',
  );

}